name: Build and deploy Docker container to Azure Web App - hemis

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: crvtdfxkgx6qofq.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t crvtdfxkgx6qofq.azurecr.io/hemis:latest .
          docker push crvtdfxkgx6qofq.azurecr.io/hemis:latest

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-push
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Log in to Azure using OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      # Step 2: Configure the Web App to use the container from ACR
      - name: Configure Azure Web App for Containers
        run: |
          az webapp config container set \
            --resource-group hemis \
            --name hemis \
            --docker-custom-image-name crvtdfxkgx6qofq.azurecr.io/hemis:latest \
            --docker-registry-server-url https://crvtdfxkgx6qofq.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      # Step 3: Restart the Azure Web App
      - name: Restart Web App
        run: |
          az webapp restart --resource-group hemis --name hemis
